model:
  arch: proteinchat
  model_type: pretrain_vicuna
  freeze_protein_encoder: True
  freeze_qformer: True
  freeze_llama: False
  freeze_lp: True

  llama_model: "/data2/zhaoyang/vicuna-weights"
  
  # generation configs
  prompt: ""

  max_txt_len: 405
  end_sym: "###"
  low_resource: True

  ##########
  # JE
  ##########
  peft_ckpt: "[stage2 chkpoint]" #"/data2/zhaoyang/protein/proteinchat_output/exp2-stage2-new/20241225035/checkpoint_19.pth" # stage-2 ckpt
  stage1_ckpt: "[stage1 chkpoint]" #"/data2/zhaoyang/protein/proteinchat_output/exp2-stage1-new/20241224200/checkpoint_29.pth" # stage-1 ckpt

datasets:
  seq:
    data_type: protein # JE-Q .. what is thi type?
    build_info:
      train:
        storage: data
  ##########
  # JE
  ##########
  dna_seq:
    data_type: microorganism
    build_info:
      train:
        storage: data

run:
  task: protein_text_pretrain # JE-Q
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  printable: True