model:
  arch: proteinchat
  model_type: pretrain_vicuna

  # Stage 1
  freeze_protein_encoder: False
  ##########
  # JE
  ##########
  freeze_microoganism_encoder: False
  freeze_lp: False
  freeze_llama: True

  # Stage 2
  # freeze_protein_encoder: True
  # freeze_lp: True
  # freeze_llama: False

  llama_model: "/home/je/.cache/huggingface/hub/models--lmsys--vicuna-13b-v1.5/snapshots/c8327bf999adbd2efe2e75f6509fa01436100dc2"
  #llama_model: "/home/je/.cache/huggingface/hub/models--lmsys--vicuna-8b-v1.5/snapshots/3321f76e3f527bd14065daf69dad9344000a201d"
  prompt: ""

  max_txt_len: 405
  end_sym: "###"
  low_resource: False
  embedding_agg: 1
  peft_ckpt: ''
  stage1_ckpt: ''

datasets:
  seq:
    data_type: protein
    build_info:
      train:
        storage: /home/je/amp-foundation-model/data
  ##########
  # JE
  ##########
  #  dna_seq:
  #    data_type: microorganism 
  #    build_info:
  #      train:
  #        storage: /home/je/amp-foundation-model/data
  #

run:
  task: protein_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6
  accum_grad_iters: 4

  weight_decay: 0.05
  max_epoch: 30
  # max_iters: 10
  # iters_per_inner_epoch: 2
  # total 3043 6 568
  iters_per_epoch: 3043
  batch_size_train: 1
  batch_size_eval: 1
  num_workers: 4
  warmup_steps: 2000

  seed: 42
  ##########
  # JE
  ##########
  output_dir: "[stage1 output path]"

  amp: True
  resume_ckpt_path: null

  printable: False # whether all ranks can print (True) or only rank 0 can print (False)

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 2 #1 #JE
  gpu: [0, 1] #JE
  dist_url: "env://"
  distributed: False #True #JE
  use_dist_eval_sampler: False
