model:
  arch: proteinchat
  model_type: pretrain_vicuna

  # Stage 1
  # freeze_protein_encoder: True
  # freeze_lp: False
  # freeze_llama: True

  # Stage 2
  freeze_protein_encoder: True
  ##########
  # JE
  ##########
  freeze_microoganism_encoder: False

  freeze_str_encoder: True
  freeze_lp: True
  freeze_llama: False

  llama_model: " ~/.cache/huggingface/hub/models--lmsys--vicuna-13b-v1.5/"
  prompt: ""

  max_txt_len: 405
  end_sym: "###"
  low_resource: False
  embedding_agg: 1
  peft_ckpt: ''
  ##########
  # JE
  ##########
  stage1_ckpt: '[checkpoint from previous stage1]' #"/data2/zhaoyang/protein/proteinchat_output/exp2-stage1-new/20241224200/checkpoint_29.pth"
  alphafold_params: "/data2/zhaoyang/alphafold"
  alphafold_model_type": "model_1"
  
datasets:
  seq:
    data_type: protein
    build_info:
      train:
        storage:  /home/je/amp-foundation-model/data
  ##########
  # JE
  ##########
  dna_seq:
    data_type: microorganism
    build_info:
      train:
        storage:  /home/je/amp-foundation-model/data

run:
  task: protein_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 5e-6
  min_lr: 5e-6
  warmup_lr: 5e-6
  accum_grad_iters: 4

  weight_decay: 0.01
  max_epoch: 20
  iters_per_epoch: 3043
  batch_size_train: 1
  batch_size_eval: 1
  num_workers: 4
  warmup_steps: 0

  seed: 42
  ##########
  # JE
  ##########
  output_dir: "[output path]"

  amp: True
  resume_ckpt_path: null

  printable: False # whether all ranks can print (True) or only rank 0 can print (False)

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
